I did all of the required exercises and understand them fully.

# 6.3 What does this Code Do?

The dictionary `temperatures` contains three Fahrenheit temperature samples for each of four days. What does the `for` statement do?

The above code prints the average temperature on each day. For each item in the dictionary, the code prints the dictionary key, which is a day of the week, and then calculates the average of the value, which is a list of the temperatures on that day. It then prints the average.

# 6.6 Data Science: Duplicate Word Removal

Write a function that receives a list of words, then determines and displays in alphabetical order only the unique words. Treat uppercase and lowercase letters the same. The function should use a set to get the unique words in the list. Test your function with several sentences.

In [1]:
def remove_duplicates(words):
    """Receives a list of words and displays only the unique words in alphabetical order."""
    return sorted(set(word.lower() for word in words))

In [2]:
remove_duplicates(['Hi', 'how', 'are', 'you'])

['are', 'hi', 'how', 'you']

In [3]:
remove_duplicates(['Go', 'Warriors'])

['go', 'warriors']

In [4]:
remove_duplicates(['hi', 'hi'])

['hi']

In [5]:
remove_duplicates(['Hi', 'how', 'are', 'you', 'hi'])

['are', 'hi', 'how', 'you']

# 6.9 Dictionary Manipulations

Using the following dictionary, which maps country names to Internet top-level domains (TLDs):

In [7]:
tlds = {'Canada': 'ca', 'United States': 'us', 'Mexico': 'mx'}

## A. Check whether the dictionary contains the key 'Canada'.

In [8]:
'Canada' in tlds

True

## B. Check whether the dictionary contains the key 'France'.

In [9]:
'France' in tlds

False

## C. Iterate through the key–value pairs and display them in two-column format.

In [12]:
#Print columns
for k, v in tlds.items():
    print(f'{k:20}{v}')

Canada              ca
United States       us
Mexico              mx


## D. Add the key–value pair 'Sweden' and 'sw' (which is incorrect).

In [2]:
tlds['Sweden'] = 'sw'

In [3]:
tlds

{'Canada': 'ca', 'United States': 'us', 'Mexico': 'mx', 'Sweden': 'sw'}

## E. Update the value for the key 'Sweden' to 'se'.

In [4]:
tlds['Sweden'] = 'se'

In [5]:
tlds

{'Canada': 'ca', 'United States': 'us', 'Mexico': 'mx', 'Sweden': 'se'}

## F. Use a dictionary comprehension to reverse the keys and values.

In [52]:
tlds = {v: k for k, v in tlds.items()}

In [53]:
tlds

{'ca': 'Canada', 'us': 'United States', 'mx': 'Mexico', 'se': 'Sweden'}

## G. With the result of part (f), use a dictionary comprehension to convert the country names to all uppercase letters.



In [55]:
tlds = {k: v.upper() for k, v in tlds.items()}

In [56]:
tlds

{'ca': 'CANADA', 'us': 'UNITED STATES', 'mx': 'MEXICO', 'se': 'SWEDEN'}

# 7.2 Broadcasting

Use arange to create a 2-by-2 array containing the numbers 0–3. Use broadcasting to perform each of the following operations on the original array:

In [14]:
import numpy as np

In [24]:
numbers = np.arange(4)
numbers = numbers.reshape(2, 2)

In [16]:
numbers

array([[0, 1],
       [2, 3]])

## A. Cube every element of the array.

In [17]:
numbers ** 3

array([[ 0,  1],
       [ 8, 27]], dtype=int32)

## B. Add 7 to every element of the array.

In [18]:
numbers + 7

array([[ 7,  8],
       [ 9, 10]])

## C. Multiply every element of the array by 2.

In [19]:
numbers * 2

array([[0, 2],
       [4, 6]])

# 7.3 Element-Wise `array` Multiplication

Create a 3-by-3 array containing the even integers from 2 through 18. Create a second 3-by-3 array containing the integers from 9 down to 1, then multiply the first array by the second.

In [25]:
first = np.arange(2, 20, 2)
first = first.reshape(3, 3)
first

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [26]:
second = np.arange(9, 0, -1)
second = second.reshape(3, 3)
second

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [23]:
first * second

array([[18, 32, 42],
       [48, 50, 48],
       [42, 32, 18]])

# 7.9 Data Science: Indexing and Slicing `arrays`

Create an array containing the values 1–15, reshape it into a 3-by-5 array, then use indexing and slicing techniques to perform each of the following operations:

In [27]:
numbers = np.arange(1, 16)
numbers = numbers.reshape(3, 5)
numbers

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

## A. Select row 2.

In [86]:
numbers[2]

array([11, 12, 13, 14, 15])

## B. Select column 5.

In [87]:
numbers[:, 4]

array([ 5, 10, 15])

## C. Select rows 0 and 1.

In [88]:
numbers[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## D. Select columns 2-4.

In [28]:
numbers[:, 2:5]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15]])

## E. Select the element that is in row 1 and column 4.

In [29]:
numbers[1, 4]

10

## F. Select all elements from rows 1 and 2 that are in columns 0, 2 and 4.

In [30]:
numbers[1:3, [0, 2, 4]]

array([[ 6,  8, 10],
       [11, 13, 15]])

# 7.14 Data Science: Horizontal and Vertical Stacking

Create the two-dimensional arrays:

In [92]:
array1 = np.array([[0, 1], [2, 3]])
array2 = np.array([[4, 5], [6, 7]])

## A. Use vertical stacking to create the 4-by-2 array named array3 with array1 stacked on top of array2.

In [103]:
array3 = np.vstack((array1, array2))

In [104]:
array3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

## B. Use horizontal stacking to create the 2-by-4 array named array4 with array2 to the right of array1.

In [95]:
array4 = np.hstack((array1, array2))

In [96]:
array4

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

## C. Use vertical stacking with two copies of array4 to create a 4-by-4 array5.

In [105]:
array5 = np.vstack((array4, array4))

In [106]:
array5

array([[0, 1, 4, 5],
       [2, 3, 6, 7],
       [0, 1, 4, 5],
       [2, 3, 6, 7]])

## D. Use horizontal stacking with two copies of array3 to create a 4-by-4 array6.

In [107]:
array6 = np.hstack((array3, array3))

In [108]:
array6

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5],
       [6, 7, 6, 7]])

In [2]:
temperatures = {
    'Monday': [66, 70, 74],
    'Tuesday': [50, 56, 64],
    'Wednesday': [75, 80, 83],
    'Thursday': [67, 74, 81]
}
for k, v in temperatures.items():
    print(f'{k}: {sum(v)/len(v):.2f}')

Monday: 70.00
Tuesday: 56.67
Wednesday: 79.33
Thursday: 74.00
